"""empty message

Revision ID: 92dd5106ee49
Revises: 1951be007688
Create Date: 2017-09-12 20:37:43.635000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '92dd5106ee49'
down_revision = '1951be007688'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', mysql.CHAR(length=128), nullable=True))
    # ### end Alembic commands ###
